// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wira

import (
	"vkc/app"
	"vkc/mgo"
	"vkc/vpp"
	"vkc/wira/module"
	"vkc/xmail"
)

// Injectors from wire.go:

// BuildInjector 生成注入器
func NewApp() (vpp.ServeRunner, func(), error) {
	httpSrvOption := vpp.UseHttpSrv0()
	engine := vpp.NewHttpSrv(httpSrvOption)
	healthz := vpp.NewHealthz(engine)
	injector := module.Injector{}
	iRouter := vpp.NewRouter(engine)
	database, cleanup, err := mgo.NewDefaultDatabase()
	if err != nil {
		return nil, nil, err
	}
	mailManager := &xmail.MailManager{
		DS: database,
	}
	email := &app.Email{
		EM: mailManager,
	}
	appInjector := app.Injector{
		Engine: engine,
		Router: iRouter,
		Email:  email,
	}
	wiraApp := &App{
		Engine: engine,
		HLZ:    healthz,
		MOD:    injector,
		APP:    appInjector,
	}
	return wiraApp, func() {
		cleanup()
	}, nil
}
