// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wira

import (
	"vkc/app"
	"vkc/vpp"
	"vkc/wira/module"
)

// Injectors from wire.go:

// BuildInjector 生成注入器
func NewApp() (vpp.ServeRunner, func(), error) {
	httpSrvOption := vpp.UseHttpSrv0()
	engine := vpp.NewHttpSrv(httpSrvOption)
	healthz := vpp.NewHealthz(engine)
	injector := module.Injector{}
	iRouter := vpp.NewRouter(engine)
	index := &app.Index{}
	demo := &app.Demo{}
	appInjector := app.Injector{
		Engine: engine,
		Router: iRouter,
		Index:  index,
		Demo:   demo,
	}
	wiraApp := &App{
		Engine: engine,
		HLZ:    healthz,
		MOD:    injector,
		APP:    appInjector,
	}
	return wiraApp, func() {
	}, nil
}
