# 运行模式(debug:调试,test:测试,release:正式)
runmode = "release"
showsql = false
printconfig = false

[serve]
port = 80

[mongodb]
host = "xx.xx.xx.xx"
port = "27001"
username = "xx"
password = "xxxx"
database = "xx"
rawoptions = "w=majority&authSource=admin"

[xmail]
syncuri = "https://xxx"
collname = "mailx"