@BASE=http://127.0.0.1:80
@AKEY=api_u98gygzzh40yfwuylgi6paan1qrnt1zt

### 初始化访问令牌， 第一个可以初始化，之后需要修改数据库增加访问令牌
GET {{BASE}}/api/init_token

### 获取所有邮件
GET {{BASE}}/api/emls?zone=&addr=s@suisrc.cn&skip=&limit=
x-api-key: {{AKEY}}

### 获取所有邮件
GET {{BASE}}/api/emls.text?zone=&addr=&skip=&limit=2
x-api-key: {{AKEY}}

### 获取指定邮件
GET {{BASE}}/api/eml?zone=&addr=s@suisrc.cn&mid=&state=
x-api-key: {{AKEY}}

### 获取指定邮件的内容
GET {{BASE}}/api/eml.html?zone=&addr=s@suisrc.cn&mid=&state=
x-api-key: {{AKEY}}

### 获取指定邮件的内容
GET {{BASE}}/api/eml.text?zone=&mid=&state=&addr=
x-api-key: {{AKEY}}

### 增加邮件
POST {{BASE}}/api/eml
x-api-key: {{AKEY}}

### 更新邮件
PUT {{BASE}}/api/eml
x-api-key: {{AKEY}}

{
    "mid": "xxx",
    "state": 2,
}

### 删除邮件
DELETE {{BASE}}/api/eml?mid=

